sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="lokesal"
  - DOCKERHUB_ORG="wiflash"
branches:
  only:
  - release
before_install:
- openssl aes-256-cbc -K $encrypted_2de3dbc0947b_key -iv $encrypted_2de3dbc0947b_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy_rsa
after_script:
- sed -i -e 's|INI_KUNCI_LOKESAL|'"${INI_KUNCI_LOKESAL}"'|g' ./Dockerfile
- sed -i -e 's|INI_EMAIL_LOKESAL|'"${INI_EMAIL_LOKESAL}"'|g' ./Dockerfile
- sed -i -e 's|INI_PWD_LOKESAL|'"${INI_PWD_LOKESAL}"'|g' ./Dockerfile
- sed -i -e 's|FLASK_ENV|'"${FLASK_ENV}"'|g' ./Dockerfile
- sed -i -e 's|INI_UNAME|'"${INI_UNAME}"'|g' ./Dockerfile
- sed -i -e 's|INI_PWD|'"${INI_PWD}"'|g' ./Dockerfile
- sed -i -e 's|INI_DB_ENDPOINT|'"${INI_DB_ENDPOINT}"'|g' ./Dockerfile
- sed -i -e 's|INI_DB_TEST|'"${INI_DB_TEST}"'|g' ./Dockerfile
- sed -i -e 's|INI_DB_DEV|'"${INI_DB_DEV}"'|g' ./Dockerfile
- sed -i -e 's|DOCKERHUB_USER|'"${DOCKERHUB_USER}"'|g' ~/.docker-profile
- sed -i -e 's|DOCKERHUB_PASS|'"${DOCKERHUB_PASS}"'|g' ~/.docker-profile
- docker build -t ${DOCKERHUB_ORG}/${DOCKER_IMAGE_NAME}:be-${TRAVIS_BUILD_ID} .
- docker push ${DOCKERHUB_ORG}/${DOCKER_IMAGE_NAME}:be-${TRAVIS_BUILD_ID}
- docker tag ${DOCKERHUB_ORG}/${DOCKER_IMAGE_NAME}:be-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:be-latest
- docker push ${DOCKERHUB_ORG}/${DOCKER_IMAGE_NAME}:be-latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh
