"""empty message

Revision ID: 212d678223f3
Revises: 9954331f0886
Create Date: 2020-02-11 20:07:08.413928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212d678223f3'
down_revision = '9954331f0886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keluhan', 'total_dukungan')
    op.drop_column('keluhan', 'total_komentar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keluhan', sa.Column('total_komentar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('keluhan', sa.Column('total_dukungan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
