"""empty message

Revision ID: 9954331f0886
Revises: 
Create Date: 2020-02-05 12:12:28.490880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9954331f0886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keluhan', sa.Column('kepuasan', sa.Boolean(), nullable=True))
    op.alter_column('keluhan', 'dibuat',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('keluhan', 'diperbarui',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pengguna', 'dibuat',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pengguna', 'diperbarui',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pengguna', 'diperbarui',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pengguna', 'dibuat',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('keluhan', 'diperbarui',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('keluhan', 'dibuat',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('keluhan', 'kepuasan')
    # ### end Alembic commands ###
